insert into Categories (Name, Description) values ('Web Development', 'Learn how to design, develop, and deploy responsive websites.');
insert into Categories (Name, Description) values ('Data Science', 'Analyze complex datasets to extract meaningful insights.');
insert into Categories (Name, Description) values ('Cybersecurity', 'Protect systems and networks from cyber threats.');
insert into Categories (Name, Description) values ('Mobile App Development', 'Build engaging mobile applications for Android and iOS.');
insert into Categories (Name, Description) values ('Cloud Computing', 'Master cloud platforms like AWS, Azure, and Google Cloud.');
insert into Categories (Name, Description) values ('UI/UX Design', 'Design intuitive and beautiful user interfaces and experiences.');
insert into Categories (Name, Description) values ('Artificial Intelligence', 'Create smart systems that learn and adapt using AI.');
insert into Categories (Name, Description) values ('DevOps', 'Integrate development and operations for faster software delivery.');
insert into Categories (Name, Description) values ('Soft Skills', 'Improve communication, teamwork, and leadership abilities.');
insert into Categories (Name, Description) values ('Game Development', 'Design and program engaging games using modern engines.');
insert into Categories (Name, Description) values ('Quran Memorization', 'Memorize the Holy Quran with effective techniques and guidance.');
insert into Categories (Name, Description) values ('Tajweed Rules', 'Learn the rules for proper recitation of the Quran.');
insert into Categories (Name, Description) values ('Hadith Studies', 'Study the sayings and traditions of the Prophet Muhammad ﷺ.');
insert into Categories (Name, Description) values ('Islamic Jurisprudence', 'Explore the science of Islamic laws and rulings (Fiqh).');
insert into Categories (Name, Description) values ('Seerah', 'Learn about the life and biography of the Prophet Muhammad ﷺ.');
insert into Categories (Name, Description) values ('Supplications (Dua)', 'Study and memorize authentic daily and special Islamic supplications.');
